Repository hhyo/Archery, pull requests merged in 2019-08, with the labels that each got.

#334 添加 pgsql 上线功能
  sql/engines/pgsql.py
  sql/engines/tests.py
  sql/instance.py
  sql/query.py
Labels: enhancement

#385 Feat: add info api
  .coveragerc
  archery/__init__.py
  archery/settings.py
  archery/urls.py
  common/templates/base.html
  common/templates/login.html
  common/utils/global_info.py
  sql_api/__init__.py
  sql_api/apps.py
  sql_api/tests.py
  sql_api/urls.py
  sql_api/views.py
Labels: area/administration, enhancement

#408 增加对Phoenix的支持
  requirements.txt
  sql/engines/__init__.py
  sql/engines/phoenix.py
  sql/models.py
  sql/templates/instance.html
  sql/templates/queryapplylist.html
  sql/templates/sqlquery.html
  sql/templates/sqlsubmit.html
Labels: enhancement

#418 调整JSON序列化的时间格式，fix #414
  common/utils/extend_json_encoder.py
Labels: bug

#420 修复脱敏异常时将权限校验标记为跳过的问题
  sql/query.py
Labels: bug

#421 删除readthedocs文档
  docs/FAQ.md
  docs/config.md
  docs/index.md
  docs/installation.md
  docs/mysql_db_design_guide.docx
  docs/mysql_db_design_guide.md
  docs/quickstart.md
  docs/related_docs.md
  docs/requirements.txt
  docs/user_guide.md
  mkdocs.yml
Labels: skip-changelog
