Repository hhyo/Archery, pull requests merged in 2019-05, with the labels that each got.

#167 修改mssql对应的use语句， 规避特殊符号问题
  sql/engines/mssql.py
Labels: bug

#178 添加手动执行功能
  common/static/dist/js/formatter.js
  requirements.txt
  sql/locale/zh_Hans/LC_MESSAGES/django.po
  sql/locale/zh_Hans/LC_MESSAGES/djangojs.po
  sql/models.py
  sql/sql_workflow.py
  sql/templates/detail.html
  sql/tests.py
Labels: enhancement

#215 修复连接检测bug
  sql/engines/oracle.py
  sql/engines/tests.py
Labels: enhancement

#212 新增mssql 执行
  sql/engines/models.py
  sql/engines/mssql.py
  sql/engines/tests.py
Labels: enhancement

#230 qcluster 启动方式改为supervisor启动, 增加稳定性
  qcluster_supervisord.conf
  requirements.txt
  src/docker/startup.sh
  startup.sh
Labels: area/docker, area/qcluster, bug
