Repository hhyo/Archery, pull requests merged in 2019-11, with the labels that each got.

#475 增加脚本一键初始化脚本
  src/charts/README.md
  src/charts/templates/deployment.yaml
  src/charts/templates/ingress.yaml
  src/charts/values.yaml
Labels: enhancement

#504 工单提醒页工单过滤bugfix
  common/workflow.py
Labels: 请提供更多信息

#511 增加数据字典导出功能
  archery/__init__.py
  requirements.txt
  sql/data_dictionary.py
  sql/engines/mysql.py
  sql/models.py
  sql/templates/data_dictionary.html
  sql/tests.py
  sql/urls.py
  sql/utils/sql_utils.py
  sql/utils/tests.py
  src/docker/Dockerfile
  src/init_sql/v1.7.1_v1.7.2.sql
Labels: enhancement

#518 优化回滚查询，支持下载回滚语句，方便回滚
  sql/engines/inception.py
  sql/templates/detail.html
  sql/views.py
Labels: enhancement

#532 fixed bug, when we change group_name select element, the optgroup of …
  sql/templates/sqlsubmit.html
Labels: bug

#528 Feature/dockerfile
  .gitignore
  src/docker/Dockerfile
  src/docker/Dockerfile-base
Labels: enhancement

#539 SQL上线工单增加需求链接，方便追溯变更需求信息 #526
  sql/models.py
  sql/sql_workflow.py
  sql/templates/detail.html
  sql/templates/sqlsubmit.html
  sql/tests.py
  src/init_sql/v1.7.2_v1.7.3.sql
Labels: enhancement
