Repository hhyo/Archery, pull requests merged in 2019-09, with the labels that each got.

#438 bugfix: 为 failed_login_count 增加范围限制, 强制限制在 0-127
  sql/models.py
  sql/tests.py
Labels: bug

#422 使用新版pyecharts实现数据可视化
  common/dashboard.py
  common/templates/dashboard.html
  common/utils/chart_dao.py
  requirements.txt
Labels: area/frontend, enhancement

#447 Feature/ding2person
  archery/settings.py
  common/auth.py
  common/templates/config.html
  sql/admin.py
  sql/models.py
  sql/notify.py
  sql/tasks/ding.py
  sql/utils/ding_api.py
  src/docker-compose/archery/settings.py
  src/init_sql/v1.6.7_v1.7.0.sql
Labels: enhancement

#452 完善 MySQL 账号管理，支持新增、授权、改密和删除
  common/templates/base.html
  requirements.txt
  sql/admin.py
  sql/db_diagnostic.py
  sql/instance.py
  sql/instance_account.py
  sql/models.py
  sql/templates/dbdiagnostic.html
  sql/templates/instanceaccount.html
  sql/templates/instanceuser.html
  sql/urls.py
  sql/views.py
  src/init_sql/v1.6.7_v1.7.0.sql
Labels: enhancement

#457 增加 MySQL 实例数据库管理模块
  common/templates/base.html
  sql/instance_database.py
  sql/models.py
  sql/templates/database.html
  sql/urls.py
  sql/views.py
  src/init_sql/v1.6.7_v1.7.0.sql
Labels: enhancement
