Repository hhyo/Archery, pull requests merged in 2020-01, with the labels that each got.

#602 修复企业微信发送消息失败的bug
  common/utils/wx_api.py
Labels: 请提供更多信息

#603 解决部分页面SQL内容未转义，导致展示异常的问题
  sql/sql_workflow.py
  sql/templates/detail.html
  sql/templates/rollback.html
  sql/templates/sqladvisor.html
  sql/templates/sqlanalyze.html
  sql/templates/sqlquery.html
  sql/templates/sqlsubmit.html
  sql/tests.py
  sql/urls.py
  sql/views.py
Labels: bug

#600 新增在线体验域名
  README.md
Labels: enhancement

#617 增加MySQL数据归档模块，使用pt-archiver归档数据
  archery/__init__.py
  common/templates/base.html
  common/templates/config.html
  common/utils/const.py
  sql/admin.py
  sql/archiver.py
  sql/models.py
  sql/notify.py
  sql/plugins/pt_archiver.py
  sql/plugins/tests.py
  sql/resource_group.py
  sql/templates/archive.html
  sql/templates/archivedetail.html
  sql/tests.py
  sql/urls.py
  sql/utils/tests.py
  sql/utils/workflow_audit.py
  sql/views.py
  src/docker/Dockerfile-base
  src/init_sql/v1.7.4_v1.7.5.sql
Labels: enhancement
