Repository hhyo/Archery, pull requests merged in 2020-02, with the labels that each got.

#620 调整资源组和实例标签的多对多模型，使用Django默认的中间表
  archery/__init__.py
  common/auth.py
  common/tests.py
  sql/admin.py
  sql/instance.py
  sql/models.py
  sql/resource_group.py
  sql/templates/groupmgmt.html
  sql/tests.py
  sql/utils/resource_group.py
  sql/utils/sql_review.py
  sql/utils/tests.py
  src/init_sql/v1.7.6_v1.7.7.sql
Labels: ease of use, enhancement

#618 mongodb支持非root用户连接
  common/check.py
  common/static/toastr/toastr.min.css
  common/static/toastr/toastr.min.js
  common/tests.py
  sql/engines/__init__.py
  sql/engines/mongo.py
  sql/engines/mssql.py
  sql/engines/mysql.py
  sql/engines/oracle.py
  sql/engines/pgsql.py
  sql/engines/phoenix.py
  sql/engines/redis.py
  sql/engines/tests.py
  sql/instance.py
  sql/models.py
  sql/query.py
  sql/templates/sqlquery.html
  sql/tests.py
  src/init_sql/v1.7.6_v1.7.7.sql
Labels: enhancement

#623 初始化数据增加几个默认权限组
  README.md
  sql/fixtures/auth_group.sql
  sql/fixtures/initial_data.json
Labels: ease of use

#646 一体初始化脚本
  admin.sh
Labels: ease of use
